name: wellness
description: A Flutter project for Firebase Email/Password Authentication
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Icons and media
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.3.1
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.9

  # Firebase for authentication
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  cloud_firestore: ^5.6.11


  # Optional: Google Sign-In (if needed in future)
  google_sign_in: ^6.1.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/avatar.png
    - assets/images/mail.png
    - assets/images/lock.png
    - assets/images/person.png
    - assets/images/google.png

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
